### ISSUE TITLE
Token Accuracy

### ISSUE THREAD

**Issue by jndevanshu** [gokulchittaranjan/fire2014translit_subtask1#1]
I am guessing that it calculates the percentage of tokens that were labelled correctly. However, when I tried my program, it is not giving me the correct value. On inspecting the code, I found that token accuracy is being calculated wrongly : numerator and denominator are switched. Please correct the same.

**Comment by gokulchittaranjan** [comment]
Hi Devanshu, Thanks for the feedback.
Can you please provide an example that shows that the computation is wrong?
Also, what lines of code are you referring to, as being incorrect?

**Comment by jndevanshu** [comment]
Hi,
I have attached a snapshot showing the token accuracy to be greater than 100.
<img width="1083" alt="screen shot 2015-09-23 at 17 50 06" src="https://cloud.githubusercontent.com/assets/5813054/10044912/03102b8e-621c-11e5-8bd6-e0274adc78f6.png">

In the code, at line 151, I think that the numerator and denominator are interchanged. I am attaching a snapshot of the same too.
<img width="944" alt="screen shot 2015-09-23 at 17 51 54" src="https://cloud.githubusercontent.com/assets/5813054/10044913/055b6d9a-621c-11e5-92c9-30d505169417.png">

Regards
Devanshu Jain

**Comment by gokulchittaranjan** [comment]
Thanks. Fixed.
